<?php


namespace App\Classes;


class Response
{
    const USER_HAS_VOTED_BEFORE=1;
    const DATABASE_ERROR_ON_INSERTING_USER_VOTE = 2;
    const DATABASE_ERROR_ON_INSERTING_VOTE=3;
    const DATABASE_ERROR_ON_UPDATING_VOTE=4;
    const DATABASE_ERROR_ON_DELETING_VOTE=5;
    const DATABASE_ERROR_ON_INSERTING_OPTION=6;
    const DATABASE_ERROR_ON_UPDATING_OPTION=6;
    const DATABASE_ERROR_ON_DELETING_OPTION=6;
}
